- default:
  - workers:
    - wrk: "kube-node3"
    - wrk: "kube-node2"
    strategy: platform
    invalidate:
      - max_concurrent_invocations: 100
      - capacity_used: 50
  - workers:
    - wrk: "kube-node3"
    - wrk: "kube-node2"
    strategy: random
  - workers:
    - wrk: "kube-node2"
  strategy: "random"
- mongoDB:
  - controller: "kube-node4"
    workers:
    - set:
    topology_tolerance: "all"
    strategy: random
  - controller: "kube-node5"
    workers:
    - set: "kube-label3"
      strategy: random
    - set: "kube-label2"
      strategy: platform
    - set:
      strategy: random
    topology_tolerance: "none"
    strategy: platform
  strategy: random
  followup: default
