default:
  blocks:
    - controller: "*"
      workers:
      - "kube-node3"
      - "kube-node2"
      strategy: platform
      invalidate:
        - max_concurrent_invocations: 100
        - capacity_used: 50
    - workers:
      - "kube-node3"
      - "kube-node2"
      strategy: random
    - workers:
      - "kube-node2"
  strategy: "random"
mongoDB:
  blocks:
    - controller: "kube-node4"
      workers: "*"
      topology_tolerance: "all"
      strategy: random
    - controller: "kube-node5"
      workers:
      - label: "*kube-label3"
        strategy: random
      - label: "*kube-label2"
        strategy: platform
      - label: "*"
        strategy: random
      topology_tolerance: "none"
      strategy: platform
  strategy: random
  followup: default
